[2024-11-24T04:24:49.133+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-24T04:24:49.154+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_postgresql_2.extract_attendance_data manual__2024-11-23T11:09:01.750747+00:00 [queued]>
[2024-11-24T04:24:49.162+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_postgresql_2.extract_attendance_data manual__2024-11-23T11:09:01.750747+00:00 [queued]>
[2024-11-24T04:24:49.163+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 4
[2024-11-24T04:24:49.179+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): extract_attendance_data> on 2024-11-23 11:09:01.750747+00:00
[2024-11-24T04:24:49.191+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=29033) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-24T04:24:49.191+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'api_to_postgresql_2', 'extract_attendance_data', 'manual__2024-11-23T11:09:01.750747+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/api_to_pgdatabase.py', '--cfg-path', '/tmp/tmp2jszt_tn']
[2024-11-24T04:24:49.193+0000] {standard_task_runner.py:72} INFO - Started process 29034 to run task
[2024-11-24T04:24:49.193+0000] {standard_task_runner.py:105} INFO - Job 40: Subtask extract_attendance_data
[2024-11-24T04:24:49.259+0000] {task_command.py:467} INFO - Running <TaskInstance: api_to_postgresql_2.extract_attendance_data manual__2024-11-23T11:09:01.750747+00:00 [running]> on host 91b3e7b0f6a8
[2024-11-24T04:24:49.391+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_postgresql_2' AIRFLOW_CTX_TASK_ID='extract_attendance_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-23T11:09:01.750747+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-23T11:09:01.750747+00:00'
[2024-11-24T04:24:49.396+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-24T04:24:49.398+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-24T04:24:49.400+0000] {logging_mixin.py:190} INFO - Current task name:extract_attendance_data state:running start_date:2024-11-24 04:24:49.154896+00:00
[2024-11-24T04:24:49.401+0000] {logging_mixin.py:190} INFO - Dag name:api_to_postgresql_2 and current dag run status:running
[2024-11-24T04:24:49.402+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-24T04:24:49.417+0000] {base.py:84} INFO - Retrieving connection 'attendance_api'
[2024-11-24T04:25:29.561+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-11-24T04:25:29.563+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-24T04:25:29.598+0000] {process_utils.py:132} INFO - Sending 15 to group 29034. PIDs of all processes in the group: [29034]
[2024-11-24T04:25:29.598+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 29034
[2024-11-24T04:25:29.599+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-24T04:25:29.622+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-24T04:25:29.653+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=29034, status='terminated', exitcode=0, started='04:24:48') (29034) terminated with exit code 0
